"""add_ml_columns_to_snapshots

Revision ID: 20422c79793d
Revises: cd66bf77eecd
Create Date: 2026-06-28 22:51:20.368821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20422c79793d'
down_revision: Union[str, Sequence[str], None] = 'cd66bf77eecd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ml2_training_runs')
    with op.batch_alter_table('screening_snapshots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ml_prediction', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ml_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ml_label', sa.String(length=20), nullable=True))
        batch_op.drop_column('ml2_signal')
        batch_op.drop_column('ml2_p_sl')
        batch_op.drop_column('ml2_rank')
        batch_op.drop_column('ml2_p_tp')
        batch_op.drop_column('ml2_ev_score')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('screening_snapshots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ml2_ev_score', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('ml2_p_tp', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('ml2_rank', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('ml2_p_sl', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('ml2_signal', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_column('ml_label')
        batch_op.drop_column('ml_rank')
        batch_op.drop_column('ml_prediction')

    op.create_table('ml2_training_runs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('version', sa.VARCHAR(length=30), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('num_folds', sa.INTEGER(), nullable=True),
    sa.Column('dataset_rows', sa.INTEGER(), nullable=True),
    sa.Column('date_range_start', sa.DATE(), nullable=True),
    sa.Column('date_range_end', sa.DATE(), nullable=True),
    sa.Column('mean_ic_ptp', sa.FLOAT(), nullable=True),
    sa.Column('fold_metrics', sa.TEXT(), nullable=True),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('started_at', sa.DATETIME(), nullable=False),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
