"""Add indicators and market structures

Revision ID: 3009b1535175
Revises: ffd7a6eef4c9
Create Date: 2026-05-29 20:11:26.385549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3009b1535175'
down_revision: Union[str, Sequence[str], None] = 'ffd7a6eef4c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_heikin_ashi',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('trading_date', sa.Date(), nullable=False),
    sa.Column('granularity', sa.String(length=10), nullable=False),
    sa.Column('open', sa.DECIMAL(precision=12, scale=4), nullable=False),
    sa.Column('high', sa.DECIMAL(precision=12, scale=4), nullable=False),
    sa.Column('low', sa.DECIMAL(precision=12, scale=4), nullable=False),
    sa.Column('close', sa.DECIMAL(precision=12, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol_id', 'trading_date', 'granularity', name='UQ_HA_Symbol_Date')
    )
    op.create_index('ix_ha_symbol_date', 'daily_heikin_ashi', ['symbol_id', 'trading_date'], unique=False)
    op.create_table('daily_indicators',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('trading_date', sa.Date(), nullable=False),
    sa.Column('granularity', sa.String(length=10), nullable=False),
    sa.Column('rsi_14', sa.Float(), nullable=True),
    sa.Column('atr_14', sa.Float(), nullable=True),
    sa.Column('sma_20', sa.Float(), nullable=True),
    sa.Column('sma_50', sa.Float(), nullable=True),
    sa.Column('sma_200', sa.Float(), nullable=True),
    sa.Column('ema_9', sa.Float(), nullable=True),
    sa.Column('ema_21', sa.Float(), nullable=True),
    sa.Column('macd_line', sa.Float(), nullable=True),
    sa.Column('macd_signal', sa.Float(), nullable=True),
    sa.Column('macd_histogram', sa.Float(), nullable=True),
    sa.Column('bb_upper', sa.Float(), nullable=True),
    sa.Column('bb_middle', sa.Float(), nullable=True),
    sa.Column('bb_lower', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol_id', 'trading_date', 'granularity', name='UQ_Indicator_Symbol_Date')
    )
    op.create_index('ix_indicators_symbol_date', 'daily_indicators', ['symbol_id', 'trading_date'], unique=False)
    op.create_table('line_break_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('line_index', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('open', sa.DECIMAL(precision=12, scale=4), nullable=False),
    sa.Column('close', sa.DECIMAL(precision=12, scale=4), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol_id', 'line_index', name='UQ_LineBreak_Symbol_Index')
    )
    op.create_index('ix_line_break_symbol_index', 'line_break_lines', ['symbol_id', 'line_index'], unique=False)
    op.create_table('renko_bricks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('brick_index', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('open', sa.DECIMAL(precision=12, scale=4), nullable=False),
    sa.Column('close', sa.DECIMAL(precision=12, scale=4), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('brick_size', sa.DECIMAL(precision=12, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol_id', 'brick_index', name='UQ_Renko_Symbol_Index')
    )
    op.create_index('ix_renko_symbol_index', 'renko_bricks', ['symbol_id', 'brick_index'], unique=False)
    op.create_table('screening_snapshots',
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.NVARCHAR(length=50), nullable=False),
    sa.Column('company_name', sa.NVARCHAR(length=255), nullable=False),
    sa.Column('last_trading_date', sa.Date(), nullable=False),
    sa.Column('close_price', sa.DECIMAL(precision=12, scale=4), nullable=False),
    sa.Column('price_pct_change', sa.Float(), nullable=True),
    sa.Column('volume', sa.BIGINT(), nullable=False),
    sa.Column('ha_close', sa.DECIMAL(precision=12, scale=4), nullable=False),
    sa.Column('ha_direction', sa.String(length=10), nullable=False),
    sa.Column('rsi_14', sa.Float(), nullable=True),
    sa.Column('sma_20_cross_direction', sa.String(length=10), nullable=True),
    sa.Column('sma_50_cross_direction', sa.String(length=10), nullable=True),
    sa.Column('sma_200_cross_direction', sa.String(length=10), nullable=True),
    sa.Column('macd_trend', sa.String(length=10), nullable=True),
    sa.Column('renko_direction', sa.String(length=10), nullable=True),
    sa.Column('line_break_direction', sa.String(length=10), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('symbol_id')
    )
    op.create_index('ix_snapshot_rsi', 'screening_snapshots', ['rsi_14'], unique=False)
    op.create_index('ix_snapshot_sma_200', 'screening_snapshots', ['sma_200_cross_direction'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_snapshot_sma_200', table_name='screening_snapshots')
    op.drop_index('ix_snapshot_rsi', table_name='screening_snapshots')
    op.drop_table('screening_snapshots')
    op.drop_index('ix_renko_symbol_index', table_name='renko_bricks')
    op.drop_table('renko_bricks')
    op.drop_index('ix_line_break_symbol_index', table_name='line_break_lines')
    op.drop_table('line_break_lines')
    op.drop_index('ix_indicators_symbol_date', table_name='daily_indicators')
    op.drop_table('daily_indicators')
    op.drop_index('ix_ha_symbol_date', table_name='daily_heikin_ashi')
    op.drop_table('daily_heikin_ashi')
    # ### end Alembic commands ###
