"""Initial schema

Revision ID: ffd7a6eef4c9
Revises: 
Create Date: 2026-05-29 18:55:15.739762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffd7a6eef4c9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('symbols',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.NVARCHAR(length=50), nullable=False),
    sa.Column('company_name', sa.NVARCHAR(length=255), nullable=False),
    sa.Column('isin', sa.NVARCHAR(length=50), nullable=False),
    sa.Column('series', sa.NVARCHAR(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isin')
    )
    op.create_index(op.f('ix_symbols_symbol'), 'symbols', ['symbol'], unique=True)
    op.create_table('sync_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=50), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.NVARCHAR(length=50), nullable=False),
    sa.Column('total_symbols', sa.Integer(), nullable=False),
    sa.Column('processed_symbols', sa.Integer(), nullable=False),
    sa.Column('failed_symbols', sa.Integer(), nullable=False),
    sa.Column('records_inserted', sa.Integer(), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_jobs_run_id'), 'sync_jobs', ['run_id'], unique=False)
    op.create_table('corporate_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('action_date', sa.Date(), nullable=False),
    sa.Column('action_type', sa.NVARCHAR(length=50), nullable=False),
    sa.Column('value', sa.DECIMAL(precision=18, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol_id', 'action_date', 'action_type', name='UQ_Symbol_ActionDate_Type')
    )
    op.create_table('daily_prices',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('trading_date', sa.Date(), nullable=False),
    sa.Column('open', sa.DECIMAL(precision=18, scale=4), nullable=False),
    sa.Column('high', sa.DECIMAL(precision=18, scale=4), nullable=False),
    sa.Column('low', sa.DECIMAL(precision=18, scale=4), nullable=False),
    sa.Column('close', sa.DECIMAL(precision=18, scale=4), nullable=False),
    sa.Column('adj_close', sa.DECIMAL(precision=18, scale=4), nullable=False),
    sa.Column('volume', sa.BIGINT(), nullable=False),
    sa.Column('granularity', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol_id', 'trading_date', 'granularity', name='UQ_Symbol_Date_Granularity')
    )
    op.create_index('ix_daily_prices_symbol_date', 'daily_prices', ['symbol_id', 'trading_date'], unique=False)
    op.create_table('symbol_sync_state',
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('last_successful_sync_date', sa.Date(), nullable=False),
    sa.Column('last_attempt_status', sa.NVARCHAR(length=50), nullable=False),
    sa.Column('last_error_message', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('symbol_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('symbol_sync_state')
    op.drop_index('ix_daily_prices_symbol_date', table_name='daily_prices')
    op.drop_table('daily_prices')
    op.drop_table('corporate_actions')
    op.drop_index(op.f('ix_sync_jobs_run_id'), table_name='sync_jobs')
    op.drop_table('sync_jobs')
    op.drop_index(op.f('ix_symbols_symbol'), table_name='symbols')
    op.drop_table('symbols')
    # ### end Alembic commands ###
